config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get "posts/new"
  resources :posts, only: [:index, :new, :create, :edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :time, presence: true, numericality: {only_integer: true}
 

  validates :place, presence: true
  year_month_day = /\A\d{4}-\d{2}-\d{2}\z/
  
  validates :date, presence: true, format: { with: year_month_day }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index    
    @posts = Post.all
  end
  
  def new 
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render action: :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.update(post_params)
      redirect_to posts_path
    else
      render action: :edit 
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:time, :place, :weather, :temperature, :water_temperature,:SPG_start,:SPG_finish, :dive_start,:dive_finish,:depth,:wind_direction,:wave, :fish, :date,:impression)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diving-log</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" hreh="style.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
   <footer>
  </footer>
</html>

app/views/posts/create.html.erb
<div class="title">
  <div class="scroll">
  <h1><span>保存が完了しました!!</span></h1>
  </div>
</div>

<div class="log">
  <%= link_to(posts_path) do %>
    <button class="button">トップページ</button> 
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= form_with model: @post, local: true do |form| %>
 <table>
    <tr>
      <th><%= form.label :time, "Dive No." %></th>
      <td><%= form.text_field :time, id:"post_time" %></td>
    <tr>
    <tr>
      <th><%= form.label :place, "場所" %></th>
      <td><%= form.text_field :place, id:"post_place" %></td>
    <tr>
    <tr>
      <th> <%= form.label :weather, "天気" %></th>
      <td><%= form.text_field :weather, id:"post_weather" %></td>
    <tr>
    <tr>
      <th><%= form.label :temperature, "気温" %></th>
      <td> <%= form.text_field :temperature, id:"post_temperature"%></td>
    <tr>
    <tr>
      <th><%= form.label :water_temperature, "水温" %></th>
      <td><%= form.text_field :water_temperature, id:"water_temperature"%></td>
    <tr>
    <tr>
      <th><%= form.label :SPG_start, "残圧(開始時)" %></th>
      <td> <%= form.text_field :SPG_start, id:"SPG_start"%></td>
    <tr>
    <tr>
      <th><%= form.label :SPG_finish, "残圧(終了時)" %></th>
      <td><%= form.text_field :SPG_finish, id:"SPG＿finish"%></td>
    <tr>
    <tr>
      <th><%= form.label :dive_start, "エントリー" %></th>
      <td><%= form.text_field :dive_start, id:"divestart"%></td>
    <tr>
    <tr>
      <th><%= form.label :dive_finish, "エキジット" %></th>
      <td><%= form.text_field :dive_finish, id:"dive_finish"%></td>
    <tr>
    <tr>
      <th><%= form.label :depth, "水深" %></th>
      <td><%= form.text_field :depth, id:"depth"%></td>
    <tr>
    <tr>
      <th><%= form.label :wind_direction, "風向き" %></th>
      <td><%= form.text_field :wind_direction, id:"wind_direction"%></td>
    <tr>
    <tr>
      <th><%= form.label :wave, "波" %></th>
      <td><%= form.text_field :wave, id:"wave"%></td>
    <tr>
    <tr>
      <th><%= form.label :fish, "魚" %></th>
      <td><%= form.text_field :fish, id:"fish"%></td>
    <tr>
    <tr>
      <th><%= form.label :date, "日時" %></th>
      <td><%= form.text_field :date, id:"date"%></td>
    <tr>
    <tr>
      <th> <%= form.label :impression, "感想" %></th>
      <td><%= form.text_area :impression, id:"imperssion"%></td>
    <tr>
    <tr>
      <th>👉</th>
      <td>
        <%= link_to(posts_path) do %>
          <button class="button">トップページへ戻る</button> 
        <% end %>
        <input type="submit" class="button">
      </td>
  </table>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="top">
    Diver's log
      <%= link_to(posts_new_path) do %>
        <nav class="nav">投稿ページへ!!!</nav>
      <% end %>
  </div>
</div>

<div class="log">
    <% @posts.each do |post| %>
      <%= link_to "Dive NO.#{post.time}",post_path(post.id), class: "top"%> 
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  新規投稿ページ
</div>
<P></p>
<%= form_with model: @post, local: true do |form| %> 
  <table>
    <tr>
      <th><%= form.label :time, "Dive NO." %></th>
      <td><%= form.text_field :time, id:"post_time" %></td>
    <tr>
    <tr>
      <th><%= form.label :place, "場所" %></th>
      <td><%= form.text_field :place, id:"post_place" %></td>
    <tr>
    <tr>
      <th> <%= form.label :weather, "天気" %></th>
      <td><%= form.text_field :weather, id:"post_weather" %></td>
    <tr>
    <tr>
      <th><%= form.label :temperature, "気温" %></th>
      <td> <%= form.text_field :temperature, id:"post_temperature"%></td>
    <tr>
    <tr>
      <th><%= form.label :water_temperature, "水温" %></th>
      <td><%= form.text_field :water_temperature, id:"water_temperature"%></td>
    <tr>
    <tr>
      <th><%= form.label :SPG_start, "残圧(開始時)" %></th>
      <td> <%= form.text_field :SPG_start, id:"SPG_start"%></td>
    <tr>
    <tr>
      <th><%= form.label :SPG_finish, "残圧(終了時)" %></th>
      <td><%= form.text_field :SPG_finish, id:"SPG＿finish"%></td>
    <tr>
    <tr>
      <th><%= form.label :dive_start, "エントリー" %></th>
      <td><%= form.text_field :dive_start, id:"divestart"%></td>
    <tr>
    <tr>
      <th><%= form.label :dive_finish, "エキジット" %></th>
      <td><%= form.text_field :dive_finish, id:"dive_finish"%></td>
    <tr>
    <tr>
      <th><%= form.label :depth, "水深" %></th>
      <td><%= form.text_field :depth, id:"depth"%></td>
    <tr>
    <tr>
      <th><%= form.label :wind_direction, "風向き" %></th>
      <td><%= form.text_field :wind_direction, id:"wind_direction"%></td>
    <tr>
    <tr>
      <th><%= form.label :wave, "波" %></th>
      <td><%= form.text_field :wave, id:"wave"%></td>
    <tr>
    <tr>
      <th><%= form.label :fish, "魚" %></th>
      <td><%= form.text_field :fish, id:"fish"%></td>
    <tr>
    <tr>
      <th><%= form.label :date, "日時" %></th>
      <td><%= form.text_field :date, id:"date"%></td>
    <tr>
    <tr>
      <th> <%= form.label :impression, "感想" %></th>
      <td><%= form.text_area :impression, id:"imperssion"%></td>
    <tr>
    <tr>
      <th>👉</th>
      <td>
        <%= link_to(posts_path) do %>
          <button class="button">トップページへ戻る</button> 
        <% end %>
        <input type="submit" class="button">
      </td>
    </tr>
    </table>
<% end %>

app/views/posts/show.html.erb
<table>
  <tr>
    <th>Dive No.</th>
    <td><%= @post.time %></td>
  </tr>
  <tr>
    <th>場所</th>
    <td><%= @post.place %></td>
  </tr>
  <tr>
    <th>日時</th>
    <td><%= @post.date %></td>
  <tr>
  <tr>
    <th>天気</th>
    <td><%= @post.weather %></td>
  </tr>
  <tr>
    <th>気温</th>
    <td><%= @post.temperature %></td>
  </tr>
  <tr>
    <th>水温</th>
    <td><%= @post.water_temperature %></td>
  </tr>
  <tr>
    <th>残圧(開始時)</th>
    <td><%= @post.SPG_start %></td>
  </tr>
  <tr>
    <th>残圧(終了時)</th>
    <td><%= @post.SPG_finish %></td>
  </tr>
  <tr>
    <th>エントリー</th>
    <td><%= @post.dive_start %></td>
  </tr>
  <tr>
    <th>エキジット</th>
    <td><%= @post.dive_finish %></td>
  </tr>
  <tr>
    <th>水深</th>
    <td><%= @post.depth %></td>
  </tr>
  <tr>
    <th>風向き</th>
    <td><%= @post.wind_direction %></td>
  </tr>
  <tr>
    <th>波</th>
    <td><%= @post.wave %></td>
  </tr>
  <tr>
    <th>出会った魚</th>
    <td><%= @post.fish %></td>
  </tr>
    <th>感想</th>
    <td><%= @post.impression %></td>
  </tr>
  <tr>
    <th>👉</th>
    <td>
      <%= link_to(edit_post_path) do %>
        <button class="button">編集</button>
      <% end %>
      <%= link_to(posts_path) do %>
        <button class="button">トップページへ</button> 
      <% end %>
    </td>
</table> 